# Generated by Django 5.0.4 on 2024-04-27 13:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_transancciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombr_producto', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaces.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='cliente_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaces.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaces.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 8, 17, 41, 985485))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_cliente_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaces.cliente_producto')),
                ('id_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaces.tipo_transancciones')),
            ],
        ),
    ]
