# Generated by Django 5.0.3 on 2024-03-17 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('ident_number', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 11, 2, 3, 136131))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 11, 2, 3, 136131))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 11, 2, 3, 135136))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 11, 2, 3, 135136))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
