# Generated by Django 5.0.2 on 2024-03-19 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_city_country_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='departament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='departament',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 11, 38, 1, 866983)),
        ),
    ]
